site_name: Collaborative State Machines (CSM)
repo_url: https://github.com/CollaborativeStateMachines/Cirrina
site_url: https://collaborativestatemachines.github.io/
theme:
  name: material
  font:
    text: Lato
    code: Google Sans Code
  palette:
    scheme: default
    primary: white
  language: en
  logo: https://collaborativestatemachines.github.io/assets/cirrina/icon.png
  favicon: https://collaborativestatemachines.github.io/assets/cirrina/icon.png
  icon:
    admonition:
      success: fontawesome/solid/flask
      question: fontawesome/solid/graduation-cap
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - social
    - content.code.copy
    - content.code.select
    - content.code.annotate
plugins:
  - autorefs
  - awesome-nav
  - bibtex:
      bib_file: "refs.bib"
  - search
  - git-authors
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.blocks.caption
  - footnotes
  - shadcn.extensions.iconify
  - attr_list
  - md_in_html
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js